/*
 * To change this license header, choose License Footers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view.component;

import br.com.inovatec.grid.view.component.form.Button;
import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Dimens;
import java.awt.Dimension;
import java.util.List;

/**
 *
 * @author zrobe
 */
public class FooterOptionsLayout extends javax.swing.JPanel {

    /**
     * Creates new form FooterLayout
     *
     * @param options
     */
    public FooterOptionsLayout(List<Button> options) {
        initComponents();
        addButtons(options);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsLeftPanel = new javax.swing.JPanel();
        optionsRightPanel = new javax.swing.JPanel();
        optionsCenterPanel = new javax.swing.JPanel();

        setBackground(Colors.COLOR_FOOTER);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        setPreferredSize(new Dimension(Dimens.DEFAULT_DIALOG_WIDTH, Dimens.DEFAULT_FOOTER_HEIGHT));
        setLayout(new java.awt.BorderLayout());

        optionsLeftPanel.setBackground(null);
        optionsLeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        add(optionsLeftPanel, java.awt.BorderLayout.WEST);

        optionsRightPanel.setBackground(null);
        optionsRightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        add(optionsRightPanel, java.awt.BorderLayout.EAST);

        optionsCenterPanel.setBackground(null);
        optionsCenterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        add(optionsCenterPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel optionsCenterPanel;
    private javax.swing.JPanel optionsLeftPanel;
    private javax.swing.JPanel optionsRightPanel;
    // End of variables declaration//GEN-END:variables

    private void addButtons(List<Button> options) {
        // Botoes da esquerda
        if (options != null && !options.isEmpty()) {
            for (Button b : options) {
                switch (b.getType()) {
                    case OPTION_LEFT:
                        this.optionsLeftPanel.add(b);
                        break;
                    case OPTION_CENTER:
                        this.optionsCenterPanel.add(b);
                        break;
                    case OPTION_RIGHT:
                        this.optionsRightPanel.add(b);
                        break;
                }
            }
        }
    }
    
    public void hideOptionsLeftPanel() {
        this.hideOptionsPanel(Button.ButtonType.OPTION_LEFT);
    }
    
    public void hideOptionsCenterPanel() {
        this.hideOptionsPanel(Button.ButtonType.OPTION_CENTER);
    }
    
    public void hideOptionsRightPanel() {
        this.hideOptionsPanel(Button.ButtonType.OPTION_RIGHT);
    }

    /**
     * Esconder determinado painel
     * 
     * @param type 
     */
    private void hideOptionsPanel(Button.ButtonType type) {
        switch (type) {
            case OPTION_LEFT:
                this.remove(this.optionsLeftPanel);
                break;
            case OPTION_CENTER:
                this.remove(this.optionsCenterPanel);
                break;
            case OPTION_RIGHT:
                this.remove(this.optionsRightPanel);
                break;
        }
    }

}
