/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view.component;

import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Dimens;
import br.com.inovatec.grid.view.values.Styles;
import java.awt.Dimension;
import javax.swing.Icon;

/**
 *
 * @author zrobe
 */
public class HeaderLayout extends javax.swing.JPanel {

    /**
     * Creates new form HeaderLayout
     */
    public HeaderLayout() {
        initComponents();
    }
    
    /**
     * Creates new form HeaderLayout
     * @param title
     * @param tip
     * @param icon
     */
    public HeaderLayout(String title, String tip, Icon icon) {
        initComponents();
        this.setTitle(title);
        this.setTip(tip);
        this.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        graphicElementJLabel = new javax.swing.JLabel();
        titleIconJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        tipJLabel = new javax.swing.JLabel();

        setBackground(Colors.COLOR_HEADER_TITLE);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        setPreferredSize(new Dimension(Dimens.DEFAULT_DIALOG_WIDTH, Dimens.DEFAULT_HEADER_HEIGHT));
        setLayout(new java.awt.BorderLayout());

        graphicElementJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        graphicElementJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/drawable/bg_header.png"))); // NOI18N
        graphicElementJLabel.setPreferredSize(new Dimension(120, Dimens.DEFAULT_HEADER_HEIGHT));
        add(graphicElementJLabel, java.awt.BorderLayout.LINE_END);

        titleIconJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleIconJLabel.setPreferredSize(new Dimension(51, Dimens.DEFAULT_HEADER_HEIGHT));
        add(titleIconJLabel, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(null);
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        titleJLabel.setFont(Styles.FONT_FAMILY_HEADER_LAYOUT_TITLE);
        titleJLabel.setForeground(Colors.COLOR_WHITE);
        titleJLabel.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(titleJLabel, gridBagConstraints);

        tipJLabel.setFont(Styles.FONT_FAMILY_HEADER_LAYOUT_TIP);
        tipJLabel.setForeground(Colors.COLOR_WHITE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(tipJLabel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel graphicElementJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tipJLabel;
    private javax.swing.JLabel titleIconJLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables

    public String getTitle() {
        return this.titleJLabel.getText();
    }
    
    public void setTitle(String title) {
        this.titleJLabel.setText(title);
    }
    
    public String getTip() {
        return this.tipJLabel.getText();
    }
    
    public void setTip(String tip) {
        this.tipJLabel.setText(tip);
    }
    
    public Icon getIcon() {
        return this.titleIconJLabel.getIcon();
    }
    
    public void setIcon(Icon icon) {
        this.titleIconJLabel.setIcon(icon);
    }
    
}
