/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view;

import br.com.inovatec.grid.view.util.DummyFrame;
import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Drawable;
import br.com.inovatec.grid.view.values.Styles;

/**
 *
 * @author zrobe
 */
public class SplashJFrame extends javax.swing.JDialog {

    /**
     * Creates new form Splash
     * @param dummyFrame
     */
    public SplashJFrame(DummyFrame dummyFrame) {
        super(dummyFrame.getFrame(), false);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(Colors.COLOR_INDEX_BACK);
        setMinimumSize(new java.awt.Dimension(560, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(560, 400));
        setResizable(false);

        jPanel3.setBackground(Colors.COLOR_INDEX_BACK);
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(Colors.COLOR_INDEX_BACK);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(Colors.COLOR_INDEX_BACK);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(Drawable.BG_INDEX);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(Colors.COLOR_INDEX_BACK);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(Styles.FONT_FAMILY_SPLASH);
        jLabel2.setForeground(Colors.COLOR_SPLASH_TEXT);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carregando componentes...");
        jPanel2.add(jLabel2);

        jLabel3.setFont(Styles.FONT_FAMILY_SPLASH);
        jLabel3.setForeground(Colors.COLOR_SPLASH_TEXT);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("InovaTec © 2017. Todos os direitos reservados.");
        jPanel2.add(jLabel3);

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
