/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view.component.main;

import br.com.inovatec.grid.util.object.DisciplinaTurmaAulas;
import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Cursors;
import br.com.inovatec.grid.view.values.Dimens;
import br.com.inovatec.grid.view.values.Icons;
import br.com.inovatec.grid.view.values.Styles;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author zrobe
 */
public class DisciplinaTurmaJPanel extends javax.swing.JPanel implements MouseListener {

    private boolean checked = false;
    private boolean released = true;
    private final DisciplinaTurmaAulas disciplinaTurmaAulas;
    
    /**
     * Creates new form DisciplinaTurmaJPanel
     * 
     * @param disciplinaTurmaAulas
     */
    public DisciplinaTurmaJPanel(DisciplinaTurmaAulas disciplinaTurmaAulas) {
        initComponents();
        this.disciplinaTurmaAulas = disciplinaTurmaAulas;
        init();
    }
    
    private void init() {
        // Nome
        this.nomeJLabel.setText(this.disciplinaTurmaAulas.getDisciplinaTurma().getDisciplina().getNome());
        // Icones
        this.iconJLabel.setIcon(Icons.IC_DISCIPLINA_AULA);
        this.markedJLabel.setIcon(Icons.IC_CHECK);
        this.markedJLabel.setVisible(false);
        // Mouse listener
        addMouseListener(this);
    }

    public boolean isReleased() {
        return released;
    }

    public void setReleased(boolean released) {
        this.released = released;
    }

    public boolean isChecked() {
        return checked;
    }
    
    /**
     * Bloquear painel quando estiver desabilitado
     */
    public void block() {
        this.released = false;
        this.statusJLabel.setText("0 aulas restantes");
        setBackground(Colors.COLOR_GREY);
    }
    
    /**
     * Liberar painel quando estiver habilitado
     */
    public void release() {
        this.released = true;
        this.statusJLabel.setText(this.disciplinaTurmaAulas.getTotalAulas() + (this.disciplinaTurmaAulas.getTotalAulas() == 1 ? " aula restante" : " aulas restantes"));
        setBackground(Colors.COLOR_GRADE_DISCIPLINA_TURMA_AULA_PANEL);
    }
    
    /**
     * Marcar painel
     */
    public void check() {
        this.check(!this.checked);
    }
    
    /**
     * Marcar painel
     * @param check
     */
    public void check(boolean check) {
        // Negar marcacao
        this.checked = check;
        // Exibir check
        this.markedJLabel.setVisible(this.checked);
    }

    public DisciplinaTurmaAulas getDisciplinaTurmaAulas() {
        return disciplinaTurmaAulas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicJPanel = new javax.swing.JPanel();
        columnLeftJPanel = new javax.swing.JPanel();
        iconJLabel = new javax.swing.JLabel();
        columnRightJPanel = new javax.swing.JPanel();
        markedJLabel = new javax.swing.JLabel();
        dadosJPanel = new javax.swing.JPanel();
        nomeJLabel = new javax.swing.JLabel();
        statusJLabel = new javax.swing.JLabel();

        setBackground(Colors.COLOR_HEADER_TITLE);
        setLayout(new java.awt.BorderLayout());

        graphicJPanel.setBackground(null);
        graphicJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        graphicJPanel.setLayout(new java.awt.BorderLayout());

        columnLeftJPanel.setBackground(null);
        columnLeftJPanel.setPreferredSize(new java.awt.Dimension(25, 0));

        javax.swing.GroupLayout columnLeftJPanelLayout = new javax.swing.GroupLayout(columnLeftJPanel);
        columnLeftJPanel.setLayout(columnLeftJPanelLayout);
        columnLeftJPanelLayout.setHorizontalGroup(
            columnLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        columnLeftJPanelLayout.setVerticalGroup(
            columnLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        graphicJPanel.add(columnLeftJPanel, java.awt.BorderLayout.WEST);

        iconJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconJLabel.setPreferredSize(new Dimension(51, Dimens.DEFAULT_HEADER_HEIGHT));
        graphicJPanel.add(iconJLabel, java.awt.BorderLayout.CENTER);

        columnRightJPanel.setBackground(null);
        columnRightJPanel.setPreferredSize(new java.awt.Dimension(25, 0));
        columnRightJPanel.setLayout(new java.awt.BorderLayout());

        markedJLabel.setPreferredSize(new java.awt.Dimension(25, 25));
        columnRightJPanel.add(markedJLabel, java.awt.BorderLayout.PAGE_START);

        graphicJPanel.add(columnRightJPanel, java.awt.BorderLayout.EAST);

        add(graphicJPanel, java.awt.BorderLayout.CENTER);

        dadosJPanel.setBackground(null);
        dadosJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dadosJPanel.setPreferredSize(new java.awt.Dimension(80, 60));
        dadosJPanel.setLayout(new java.awt.GridLayout(2, 0));

        nomeJLabel.setFont(Styles.FONT_FAMILY);
        nomeJLabel.setForeground(Colors.COLOR_WHITE);
        nomeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dadosJPanel.add(nomeJLabel);

        statusJLabel.setFont(Styles.FONT_FAMILY);
        statusJLabel.setForeground(Colors.COLOR_WHITE);
        statusJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dadosJPanel.add(statusJLabel);

        add(dadosJPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel columnLeftJPanel;
    private javax.swing.JPanel columnRightJPanel;
    private javax.swing.JPanel dadosJPanel;
    private javax.swing.JPanel graphicJPanel;
    private javax.swing.JLabel iconJLabel;
    private javax.swing.JLabel markedJLabel;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JLabel statusJLabel;
    // End of variables declaration//GEN-END:variables

    @Override
        public void mouseClicked(MouseEvent e) {
            
        }

        @Override
        public void mousePressed(MouseEvent e) {
            
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            if (this.released) {
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            } else {
                setCursor(Cursors.CURSOR_BLOCKED);
            }
        }

        @Override
        public void mouseExited(MouseEvent e) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
}
