/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view.component.main;

import br.com.inovatec.grid.entity.Turma;
import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Dimens;
import br.com.inovatec.grid.view.values.Styles;

/**
 *
 * @author zrobe
 */
public class GradeJPanel extends javax.swing.JPanel {

    private static final int MIN_DIAS_AULA_SIZE = 5;

    /**
     * Creates new form GradeJPanel
     * @param diasAulaSize
     * @param turma
     */
    public GradeJPanel(int diasAulaSize, Turma turma) {
        initComponents();
        this.contentJPanel.setLayout(new java.awt.GridLayout(
                1,
                diasAulaSize > MIN_DIAS_AULA_SIZE ? diasAulaSize : MIN_DIAS_AULA_SIZE,
                Dimens.DEFAULT_MIN_PADDING,
                Dimens.DEFAULT_MIN_PADDING
        ));
        StringBuilder sb = new StringBuilder(turma.getNome().toUpperCase());
        sb.append(" (");
        sb.append(turma.getSala().getNome());
        sb.append(")");
        this.titleJLabel.setText(sb.toString());
    }
    
    /**
     * Adicionar painel com novo diaAula
     * 
     * @param diaAulaJPanel 
     */
    public void addDiaAulaJPanel(DiaAulaJPanel diaAulaJPanel) {
        this.contentJPanel.add(diaAulaJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        contentJPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0));
        setLayout(new java.awt.BorderLayout());

        titleJPanel.setBackground(null);
        titleJPanel.setPreferredSize(new java.awt.Dimension(100, 50));
        titleJPanel.setLayout(new java.awt.BorderLayout());

        titleJLabel.setFont(Styles.FONT_FAMILY_HEADER_LAYOUT_TITLE);
        titleJLabel.setForeground(Colors.COLOR_MENU_BAR);
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Turma");
        titleJLabel.setPreferredSize(new java.awt.Dimension(35, 40));
        titleJPanel.add(titleJLabel, java.awt.BorderLayout.CENTER);

        add(titleJPanel, java.awt.BorderLayout.PAGE_START);

        contentJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        contentJPanel.setLayout(new java.awt.GridLayout(1, 0));
        add(contentJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentJPanel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
}
