/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view.component.form;

import br.com.inovatec.grid.view.contract.Field;
import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Styles;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JPasswordField;

/**
 *
 * @author zrobe
 */
public class PasswordTextField extends javax.swing.JPanel implements Field {

    /**
     * Creates new form TextField
     */
    public PasswordTextField() {
        initComponents();
        init();
    }
    
    /**
     * Creates new form TextField
     * @param text
     */
    public PasswordTextField(String text) {
        initComponents();
        this.jPasswordField.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createLineBorder(Colors.COLOR_BORDER_INPUT));
        setLayout(new java.awt.BorderLayout());

        jPasswordField.setFont(Styles.FONT_FAMILY);
        jPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jPasswordField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.jPasswordField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                
            }

            @Override
            public void focusLost(FocusEvent e) {
                
            }
        });
    }
    
    public void setText(String text) {
        this.jPasswordField.setText(text);
    }

    public String getText() {
        String senha = "";
        for (char c : this.jPasswordField.getPassword()) {
            senha += c;
        }
        return senha;
    }

    public JPasswordField getTextField() {
        return jPasswordField;
    }
    
    @Override
    public void setEnabled(boolean enable) {
        this.jPasswordField.setEnabled(enable);
    }
    
}
