/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.inovatec.grid.view.component.form;

import br.com.inovatec.grid.view.component.form.util.JTextFieldLimit;
import br.com.inovatec.grid.view.contract.Field;
import br.com.inovatec.grid.view.values.Colors;
import br.com.inovatec.grid.view.values.Styles;

/**
 *
 * @author zrobe
 */
public class TextArea extends javax.swing.JPanel implements Field {

    /**
     * Creates new form TextField
     */
    public TextArea() {
        initComponents();
    }
    
    /**
     * Creates new form TextField
     * @param text
     */
    public TextArea(String text) {
        initComponents();
        this.jTextArea.setText(text);
    }
    
    /**
     * Creates new form TextField
     * @param limit
     */
    public TextArea(int limit) {
        initComponents();
        this.jTextArea.setDocument(new JTextFieldLimit(limit));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setBackground(null);
        setBorder(javax.swing.BorderFactory.createLineBorder(Colors.COLOR_BORDER_INPUT));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea.setFont(Styles.FONT_FAMILY);
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setBorder(null);
        jScrollPane1.setViewportView(jTextArea);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables

    public void setText(String text) {
        this.jTextArea.setText(text);
    }

    public String getText() {
        return this.jTextArea.getText();
    }
    
    @Override
    public void setEnabled(boolean enable) {
        this.jTextArea.setEnabled(enable);
    }
    
}
